### ISSUE TITLE
Needs customer as the default role instead of 'subscriber'

### ISSUE THREAD

**Issue by ihsanberahim** [justinticktock/network-subsite-user-registration#1]
As mentioned in the setting.
`Enabling this option allows the public to register with this local site. The 'subscriber' role will be granted.`

i wants 'customer' as the default role  instead because my multisites are using woocommerce.

**Comment by ihsanberahim** [comment]
Alternatively,

* install `Debug bar` and `Debug Console`
* run script

```
update_site_option('default_user_role', 'customer');
```

**Comment by justinticktock** [comment]
well done for working it out.. yes the site default role is pulled into any new users registration.  I may make  this setting available in the plugin settings or show that its tied to the site default role somehow

**Comment by justinticktock** [comment]
I'm about to release version 2.1 of the plugin which changes this.
the default_user_role will be replace by the use of the standard WP default_role option setting.  This can now be set from the plugin settings page so you have full control.  So for your case make sure you set the role to 'customer' for the subsite after upgrading to 2.1
